services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: kafkaproducer
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --set
      - redpanda.enable_sasl=true
      - --set
      - redpanda.superusers=['myuser']
      - --kafka-addr
      - internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr
      - internal://redpanda:29092,external://localhost:9092
      - --pandaproxy-addr
      - internal://0.0.0.0:8082,external://0.0.0.0:8083
    ports:
      - "9092:9092"
      - "9644:9644"
  kafka-producer:
    build: ./producer
    container_name: instanceproducer
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:29092
      TOPIC: r023hf
      MIN_VALUE: 10
      MAX_VALUE: 50
      EVENTS_PER_SEC: 2
