services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: kafkaproducer
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
  kafka-producer:
    build: ./producer
    container_name: instanceproducer
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TOPIC: r023hf
      MIN_VALUE: 10
      MAX_VALUE: 50
      EVENTS_PER_SEC: 2
